from __future__ import annotations

from enum import StrEnum


class Intent(StrEnum):
    SP_ANALYSIS = "SP_ANALYSIS"
    METADATA_SEARCH = "METADATA_SEARCH"
    DEPENDENCY_ANALYSIS = "DEPENDENCY_ANALYSIS"
    TABLE_DESIGN = "TABLE_DESIGN"
    DRAFT_GENERATION = "DRAFT_GENERATION"
    HISTORY_LOOKUP = "HISTORY_LOOKUP"
    BLOCKED_OR_APPROVAL_REQUIRED = "BLOCKED_OR_APPROVAL_REQUIRED"
    BLOCKED = "BLOCKED"


class ArtifactType(StrEnum):
    SP_ANALYSIS_DOC = "SP_ANALYSIS_DOC"
    DEPENDENCY_REPORT = "DEPENDENCY_REPORT"
    DTO_DRAFT = "DTO_DRAFT"
    SERVICE_DRAFT = "SERVICE_DRAFT"
    MAPPER_INTERFACE = "MAPPER_INTERFACE"
    MAPPER_XML = "MAPPER_XML"


class RunStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
